### ISSUE TITLE
tests dont work on mac os

### ISSUE THREAD

**Issue by abrams27** [bazel-contrib/rules_bazel_integration_test#194]
hi, recently we bumped the version of the rules (`0.15.1` -> `0.16.0`) and our tests started failing on mac os

I think https://github.com/bazel-contrib/rules_bazel_integration_test/pull/181#issuecomment-1690173815 might be relevant

even `ProcessBuilder().command(bazelBinary, "info")` returns exit code 1

how to reproduce:
1. clone https://github.com/JetBrains/bazel-bsp
2. run `bazel test //e2e:sample_repo_test_bazel_5_3_2`
3. on linux is should pass, on mac should fail

**Comment by cgrindel** [comment]
I forked the `bazel-bsp` repo, cloned it on my Macbook Pro (x86_64) running MacOS 13.5.1, and ran `bazel test //e2e:sample_repo_test_bazel_5_3_2`. The test succeeded. What version of MacOS are you running?

**Comment by cgrindel** [comment]
I just [ran the test on a GitHub MacOS runner](https://github.com/cgrindel/bazel-bsp/actions/runs/6088971414/job/16520752374?pr=1). It worked there, as well.

**Comment by abrams27** [comment]
im using mac m2, so maybe it's arm thing?

**Comment by abrams27** [comment]
so for a runner:
```bash
#!/usr/bin/env bash

"$BIT_BAZEL_BINARY" info
```

it prints:
```
<path>/e2e/lol_bazel_6_3_2.runfiles/bazel_bsp/external/build_bazel_bazel_6_3_2/bazel_binary: line 23: <path>/e2e/lol_bazel_6_3_2.runfiles/bazel_binaries_bazelisk/bazelisk: cannot execute binary file
<path>/e2e/lol_bazel_6_3_2.runfiles/bazel_bsp/external/build_bazel_bazel_6_3_2/bazel_binary: line 23: <path>/e2e/lol_bazel_6_3_2.runfiles/bazel_binaries_bazelisk/bazelisk: Undefined error: 0
```

and apparently the tests dont work on fedora on arm as well

**Comment by katre** [comment]
I just ran into the same problem on Mac ARM silicon, so I suspect the check in [`_download_bazelisk_binary`](https://github.com/bazel-contrib/rules_bazel_integration_test/blob/main/bazel_integration_test/private/bazel_binaries.bzl#L22) is wrong.

This is tricky for me to reproduce, I don't have an intel or arm mac handy. It'd be nice if we had a canonical list of what `repository_ctx.os` could return.

**Comment by abrams27** [comment]
works on mac os m2, @tpasternak can you confirm on fedora?

**Comment by katre** [comment]
We should probably just add helpers like `_is_linux`, `_is_mac`, `_is_arm`, etc.

Also, the default fallthrough to linux/x86_64 is probably wrong, and should just be a build failure (we'd want to add the capability from #184 so people can deal with this without submitting patches to this repo).

**Comment by cgrindel** [comment]
I added the helpers and change the fallthrough to a failure. Please take a look.

**Comment by abrams27** [comment]
same here, thanks a lot!
