### ISSUE TITLE
missing @rules_shell dependency in WORKSPACE mode

### ISSUE THREAD

**Issue by aherrmann** [bazel-contrib/rules_bazel_integration_test#381]
https://github.com/bazel-contrib/rules_bazel_integration_test/pull/368 added a dependency on `rules_shell` to `rules_bazel_integration_test`, but did not add the dependency to the [`bazel_integration_test_rules_dependencies`](https://github.com/bazel-contrib/rules_bazel_integration_test/blob/9634e20cabb181d5acd0f8ee7e3358aab05a5ae8/bazel_integration_test/deps.bzl#L6) macro. Downstream users (in WORKSPACE mode) now must add rules_shell as a dependency themselves, see e.g. [this CI failure](https://github.com/aherrmann/rules_zig/actions/runs/11571741989/job/32210291866?pr=382#step:3:748).

Would it be possible to add rules_shell to `bazel_integration_test_rules_dependencies`?

**Comment by cgrindel** [comment]
Good catch! I'll try to get this updated over the weekend.
