### ISSUE TITLE
bazel_integration_test's clang dependency is unclear and probably unnecessary 

### ISSUE THREAD

**Issue by k1nkreet** [bazel-contrib/rules_bazel_integration_test#70]
`bazel_integration_test` sets `CC=clang` in test environment on linux which makes it fails in shell without clang installed in PATH. I've failed to find a reason behind it, so creating this issue to raise a question :) (or remove it if it really is unnecessary)

**Comment by cgrindel** [comment]
You may be correct. It might have been an artifact from when I was putting together the integration tests from a Swift project. Based on a quick look at the code, we will need to add code to support passing along env values. It might be as easy as removing [this](https://github.com/bazel-contrib/rules_bazel_integration_test/blob/main/bazel_integration_test/private/bazel_integration_test.bzl#L137-L141). Any integration tests that require the `CC=clang` will need to add an env.

@k1nkreet Did you want to put up a PR to address this? If not, I may be able to look at it over the weekend.

**Comment by k1nkreet** [comment]
Sure, I will
